// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PRN232_G9_AutoGradingTool.Infrastructure.Context;

#nullable disable

namespace PRN232_G9_AutoGradingTool.Infrastructure.Migrations.PRN232_G9_AutoGradingTool
{
    [DbContext(typeof(PRN232_G9_AutoGradingToolDbContext))]
    [Migration("20260416170835_ExamGradingPackAndJobs")]
    partial class ExamGradingPackAndJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("text")
                        .HasColumnName("avatar_path");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<DateTime>("JoiningAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joining_at");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_users_id");

                    b.HasIndex("JoiningAt")
                        .HasDatabaseName("ix_users_joining_at");

                    b.HasIndex("LastLoginAt")
                        .HasDatabaseName("ix_users_last_login_at")
                        .HasFilter("\"last_login_at\" IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_users_status");

                    b.HasIndex("Status", "JoiningAt")
                        .HasDatabaseName("ix_users_status_joining_at");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamGradingPack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("ExamSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_session_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_exam_grading_packs");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_examgradingpack_is_deleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_examgradingpack_status");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_examgradingpack_updated_at");

                    b.HasIndex("ExamSessionId", "IsActive")
                        .HasDatabaseName("ix_exam_grading_packs_exam_session_id_is_active");

                    b.HasIndex("ExamSessionId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_exam_grading_packs_exam_session_id_version");

                    b.HasIndex("Status", "IsDeleted")
                        .HasDatabaseName("ix_examgradingpack_status_is_deleted");

                    b.HasIndex("IsDeleted", "Status", "UpdatedAt")
                        .HasDatabaseName("ix_examgradingpack_is_deleted_status_updated_at");

                    b.ToTable("exam_grading_packs", (string)null);
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamPackAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("ExamGradingPackId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_grading_pack_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("original_file_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StorageRelativePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("storage_relative_path");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_exam_pack_assets");

                    b.HasIndex("ExamGradingPackId")
                        .HasDatabaseName("ix_exam_pack_assets_exam_grading_pack_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_exampackasset_is_deleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_exampackasset_status");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_exampackasset_updated_at");

                    b.HasIndex("Status", "IsDeleted")
                        .HasDatabaseName("ix_exampackasset_status_is_deleted");

                    b.HasIndex("IsDeleted", "Status", "UpdatedAt")
                        .HasDatabaseName("ix_exampackasset_is_deleted_status_updated_at");

                    b.ToTable("exam_pack_assets", (string)null);
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("ExamTopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_topic_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("label");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("max_score");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_exam_questions");

                    b.HasIndex("ExamTopicId")
                        .HasDatabaseName("ix_exam_questions_exam_topic_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_examquestion_is_deleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_examquestion_status");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_examquestion_updated_at");

                    b.HasIndex("Status", "IsDeleted")
                        .HasDatabaseName("ix_examquestion_status_is_deleted");

                    b.HasIndex("IsDeleted", "Status", "UpdatedAt")
                        .HasDatabaseName("ix_examquestion_is_deleted_status_updated_at");

                    b.ToTable("exam_questions", (string)null);
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamQuestionScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("ExamQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_question_id");

                    b.Property<Guid>("ExamSubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_submission_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("max_score");

                    b.Property<decimal>("Score")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("score");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_exam_question_scores");

                    b.HasIndex("ExamQuestionId")
                        .HasDatabaseName("ix_exam_question_scores_exam_question_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_examquestionscore_is_deleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_examquestionscore_status");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_examquestionscore_updated_at");

                    b.HasIndex("ExamSubmissionId", "ExamQuestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_exam_question_scores_exam_submission_id_exam_question_id");

                    b.HasIndex("Status", "IsDeleted")
                        .HasDatabaseName("ix_examquestionscore_status_is_deleted");

                    b.HasIndex("IsDeleted", "Status", "UpdatedAt")
                        .HasDatabaseName("ix_examquestionscore_is_deleted_status_updated_at");

                    b.ToTable("exam_question_scores", (string)null);
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at_utc");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("semester_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_exam_sessions");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_examsession_is_deleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_examsession_status");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_examsession_updated_at");

                    b.HasIndex("SemesterId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_exam_sessions_semester_id_code");

                    b.HasIndex("Status", "IsDeleted")
                        .HasDatabaseName("ix_examsession_status_is_deleted");

                    b.HasIndex("IsDeleted", "Status", "UpdatedAt")
                        .HasDatabaseName("ix_examsession_is_deleted_status_updated_at");

                    b.ToTable("exam_sessions", (string)null);
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid?>("ExamGradingPackId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_grading_pack_id");

                    b.Property<Guid>("ExamSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_session_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Q1ZipRelativePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("q1zip_relative_path");

                    b.Property<string>("Q2ZipRelativePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("q2zip_relative_path");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("student_code");

                    b.Property<string>("StudentName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("student_name");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<decimal?>("TotalScore")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("total_score");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("WorkflowStatus")
                        .HasColumnType("integer")
                        .HasColumnName("workflow_status");

                    b.HasKey("Id")
                        .HasName("pk_exam_submissions");

                    b.HasIndex("ExamGradingPackId")
                        .HasDatabaseName("ix_exam_submissions_exam_grading_pack_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_examsubmission_is_deleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_examsubmission_status");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_examsubmission_updated_at");

                    b.HasIndex("ExamSessionId", "StudentCode")
                        .HasDatabaseName("ix_exam_submissions_exam_session_id_student_code");

                    b.HasIndex("Status", "IsDeleted")
                        .HasDatabaseName("ix_examsubmission_status_is_deleted");

                    b.HasIndex("IsDeleted", "Status", "UpdatedAt")
                        .HasDatabaseName("ix_examsubmission_is_deleted_status_updated_at");

                    b.ToTable("exam_submissions", (string)null);
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamTestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("ExamQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_question_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("MaxPoints")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("max_points");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_exam_test_cases");

                    b.HasIndex("ExamQuestionId")
                        .HasDatabaseName("ix_exam_test_cases_exam_question_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_examtestcase_is_deleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_examtestcase_status");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_examtestcase_updated_at");

                    b.HasIndex("Status", "IsDeleted")
                        .HasDatabaseName("ix_examtestcase_status_is_deleted");

                    b.HasIndex("IsDeleted", "Status", "UpdatedAt")
                        .HasDatabaseName("ix_examtestcase_is_deleted_status_updated_at");

                    b.ToTable("exam_test_cases", (string)null);
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamTestCaseScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("ExamSubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_submission_id");

                    b.Property<Guid>("ExamTestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_test_case_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<decimal>("MaxPoints")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("max_points");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("message");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<decimal>("PointsEarned")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("points_earned");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_exam_test_case_scores");

                    b.HasIndex("ExamTestCaseId")
                        .HasDatabaseName("ix_exam_test_case_scores_exam_test_case_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_examtestcasescore_is_deleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_examtestcasescore_status");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_examtestcasescore_updated_at");

                    b.HasIndex("ExamSubmissionId", "ExamTestCaseId")
                        .IsUnique()
                        .HasDatabaseName("ix_exam_test_case_scores_exam_submission_id_exam_test_case_id");

                    b.HasIndex("Status", "IsDeleted")
                        .HasDatabaseName("ix_examtestcasescore_status_is_deleted");

                    b.HasIndex("IsDeleted", "Status", "UpdatedAt")
                        .HasDatabaseName("ix_examtestcasescore_is_deleted_status_updated_at");

                    b.ToTable("exam_test_case_scores", (string)null);
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("ExamSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_session_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_exam_topics");

                    b.HasIndex("ExamSessionId")
                        .HasDatabaseName("ix_exam_topics_exam_session_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_examtopic_is_deleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_examtopic_status");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_examtopic_updated_at");

                    b.HasIndex("Status", "IsDeleted")
                        .HasDatabaseName("ix_examtopic_status_is_deleted");

                    b.HasIndex("IsDeleted", "Status", "UpdatedAt")
                        .HasDatabaseName("ix_examtopic_is_deleted_status_updated_at");

                    b.ToTable("exam_topics", (string)null);
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.GradingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("ExamGradingPackId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_grading_pack_id");

                    b.Property<Guid>("ExamSubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_submission_id");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("JobStatus")
                        .HasColumnType("integer")
                        .HasColumnName("job_status");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_grading_jobs");

                    b.HasIndex("ExamGradingPackId")
                        .HasDatabaseName("ix_grading_jobs_exam_grading_pack_id");

                    b.HasIndex("ExamSubmissionId")
                        .HasDatabaseName("ix_grading_jobs_exam_submission_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_gradingjob_is_deleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_gradingjob_status");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_gradingjob_updated_at");

                    b.HasIndex("ExamSubmissionId", "JobStatus")
                        .HasDatabaseName("ix_grading_jobs_exam_submission_id_job_status");

                    b.HasIndex("Status", "IsDeleted")
                        .HasDatabaseName("ix_gradingjob_status_is_deleted");

                    b.HasIndex("IsDeleted", "Status", "UpdatedAt")
                        .HasDatabaseName("ix_gradingjob_is_deleted_status_updated_at");

                    b.ToTable("grading_jobs", (string)null);
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.GradingTestDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("ExamGradingPackId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_grading_pack_id");

                    b.Property<Guid?>("ExamTestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_test_case_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_grading_test_definitions");

                    b.HasIndex("ExamTestCaseId")
                        .HasDatabaseName("ix_grading_test_definitions_exam_test_case_id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_gradingtestdefinition_is_deleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_gradingtestdefinition_status");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_gradingtestdefinition_updated_at");

                    b.HasIndex("ExamGradingPackId", "SortOrder")
                        .HasDatabaseName("ix_grading_test_definitions_exam_grading_pack_id_sort_order");

                    b.HasIndex("Status", "IsDeleted")
                        .HasDatabaseName("ix_gradingtestdefinition_status_is_deleted");

                    b.HasIndex("IsDeleted", "Status", "UpdatedAt")
                        .HasDatabaseName("ix_gradingtestdefinition_is_deleted_status_updated_at");

                    b.ToTable("grading_test_definitions", (string)null);
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.Semester", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("EndDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date_utc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("StartDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_semesters");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_semesters_code");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_semester_is_deleted");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_semester_status");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_semester_updated_at");

                    b.HasIndex("Status", "IsDeleted")
                        .HasDatabaseName("ix_semester_status_is_deleted");

                    b.HasIndex("IsDeleted", "Status", "UpdatedAt")
                        .HasDatabaseName("ix_semester_is_deleted_status_updated_at");

                    b.ToTable("semesters", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamGradingPack", b =>
                {
                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.ExamSession", "ExamSession")
                        .WithMany("GradingPacks")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_grading_packs_exam_sessions_exam_session_id");

                    b.Navigation("ExamSession");
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamPackAsset", b =>
                {
                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.ExamGradingPack", "Pack")
                        .WithMany("Assets")
                        .HasForeignKey("ExamGradingPackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_pack_assets_exam_grading_packs_exam_grading_pack_id");

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamQuestion", b =>
                {
                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.ExamTopic", "ExamTopic")
                        .WithMany("Questions")
                        .HasForeignKey("ExamTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_questions_exam_topics_exam_topic_id");

                    b.Navigation("ExamTopic");
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamQuestionScore", b =>
                {
                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.ExamQuestion", "ExamQuestion")
                        .WithMany("QuestionScores")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_question_scores_exam_questions_exam_question_id");

                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.ExamSubmission", "ExamSubmission")
                        .WithMany("QuestionScores")
                        .HasForeignKey("ExamSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_question_scores_exam_submissions_exam_submission_id");

                    b.Navigation("ExamQuestion");

                    b.Navigation("ExamSubmission");
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamSession", b =>
                {
                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.Semester", "Semester")
                        .WithMany("ExamSessions")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_sessions_semesters_semester_id");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamSubmission", b =>
                {
                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.ExamGradingPack", "ExamGradingPack")
                        .WithMany()
                        .HasForeignKey("ExamGradingPackId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_exam_submissions_exam_grading_packs_exam_grading_pack_id");

                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.ExamSession", "ExamSession")
                        .WithMany("Submissions")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_submissions_exam_sessions_exam_session_id");

                    b.Navigation("ExamGradingPack");

                    b.Navigation("ExamSession");
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamTestCase", b =>
                {
                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.ExamQuestion", "ExamQuestion")
                        .WithMany("TestCases")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_test_cases_exam_questions_exam_question_id");

                    b.Navigation("ExamQuestion");
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamTestCaseScore", b =>
                {
                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.ExamSubmission", "ExamSubmission")
                        .WithMany("TestCaseScores")
                        .HasForeignKey("ExamSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_test_case_scores_exam_submissions_exam_submission_id");

                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.ExamTestCase", "ExamTestCase")
                        .WithMany("Scores")
                        .HasForeignKey("ExamTestCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_test_case_scores_exam_test_cases_exam_test_case_id");

                    b.Navigation("ExamSubmission");

                    b.Navigation("ExamTestCase");
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamTopic", b =>
                {
                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.ExamSession", "ExamSession")
                        .WithMany("Topics")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_topics_exam_sessions_exam_session_id");

                    b.Navigation("ExamSession");
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.GradingJob", b =>
                {
                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.ExamGradingPack", "Pack")
                        .WithMany("Jobs")
                        .HasForeignKey("ExamGradingPackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grading_jobs_exam_grading_packs_exam_grading_pack_id");

                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.ExamSubmission", "ExamSubmission")
                        .WithMany("GradingJobs")
                        .HasForeignKey("ExamSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grading_jobs_exam_submissions_exam_submission_id");

                    b.Navigation("ExamSubmission");

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.GradingTestDefinition", b =>
                {
                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.ExamGradingPack", "Pack")
                        .WithMany("TestDefinitions")
                        .HasForeignKey("ExamGradingPackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grading_test_definitions_exam_grading_packs_exam_grading_pa");

                    b.HasOne("PRN232_G9_AutoGradingTool.Domain.Entities.ExamTestCase", "ExamTestCase")
                        .WithMany("GradingDefinitions")
                        .HasForeignKey("ExamTestCaseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_grading_test_definitions_exam_test_cases_exam_test_case_id");

                    b.Navigation("ExamTestCase");

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamGradingPack", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Jobs");

                    b.Navigation("TestDefinitions");
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamQuestion", b =>
                {
                    b.Navigation("QuestionScores");

                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamSession", b =>
                {
                    b.Navigation("GradingPacks");

                    b.Navigation("Submissions");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamSubmission", b =>
                {
                    b.Navigation("GradingJobs");

                    b.Navigation("QuestionScores");

                    b.Navigation("TestCaseScores");
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamTestCase", b =>
                {
                    b.Navigation("GradingDefinitions");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.ExamTopic", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("PRN232_G9_AutoGradingTool.Domain.Entities.Semester", b =>
                {
                    b.Navigation("ExamSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
